### ISSUE TITLE
Still doesn't work with English interface.

### ISSUE THREAD

**Issue by grimakaka** [yandex-games-plugins/construct3#3]
You can verify this personally by simply trying to install the plugin in Construct with an English interface.
![image](https://github.com/yandex-games-plugins/construct3/assets/50794359/fd7a86fa-2ed2-4c90-8f6b-63fe8c4b2c44)
![image](https://github.com/yandex-games-plugins/construct3/assets/50794359/b54aac78-5bca-4a13-ae64-87aeeede9589)

**Comment by koteelok** [comment]
Seems to work for me?..

![image](https://github.com/yandex-games-plugins/construct3/assets/65600719/5efb4d3f-ef5c-42d5-85a6-40b591946417)

**Comment by koteelok** [comment]
Seems like that error don't accure if i use development mode.

Give me a minute, i will fix this.

**Comment by koteelok** [comment]
Version 2.0.1 should fix that issue.

[Download link.](https://github.com/yandex-games-plugins/construct3/releases/tag/YandexGamesSDK-2.0.1)

**Comment by grimakaka** [comment]
Now it works great! Thank you! Great job!
