### ISSUE TITLE
Ошибка player.getAvatarSrc is not a function при получении данных игрока

### ISSUE THREAD

**Issue by fldmit** [yandex-games-plugins/construct3#4]
Добрый день! Использую ваш пример, при запуске из консоли яндекса:

```js
Rejection from 'yagames_sdk' handler 'ysdk-get-player': TypeError: player.getAvatarSrc is not a function
    at YandexGamesSDKHandler.YSDKGetPlayer 
```

**Comment by koteelok** [comment]
Сегодня ближе к вечеру починю с новым обновлением.

**Comment by koteelok** [comment]
Должно быть пофикшено в новой версии.

https://github.com/yandex-games-plugins/construct3/releases/tag/YandexGamesSDK-2.1.0
