### ISSUE TITLE
Show rewarded запускает обычную полноэкранную рекламу. 

### ISSUE THREAD

**Issue by fldmit** [yandex-games-plugins/construct3#5]
Добрый день! 
При запуске showRewarded
![image](https://github.com/yandex-games-plugins/construct3/assets/33675542/c94b003e-cacb-4405-a43e-fc9e9dadfe01)
открывается обычная реклама. 

такая же как и при

![image](https://github.com/yandex-games-plugins/construct3/assets/33675542/7959ecd6-8ee5-4e47-b24a-8e3d636a0cac)

Если запускать напрямую 
`ysdk.adv.showRewardedVideo({`, 
то всё работает.

**Comment by koteelok** [comment]
Выпущена новая версия с решением этой проблемы!

https://github.com/yandex-games-plugins/construct3/releases/tag/YandexGamesSDK-2.1.1
