### ISSUE TITLE
Возможная ошибка

### ISSUE THREAD

**Issue by xFliTx** [yandex-games-plugins/construct3#7]
Добрый день, похоже на ошибку в адаптивном тексте:

делал ресайз выделенных объектов (мышью), в которых есть адаптивный текст, C3 выпал с ошибкой, проект сохранил, но при открытии теперь тоже ошибка. 
Видимо не нравится что-то с размером текста
Файл проекта прикладываю
[crush.zip](https://github.com/user-attachments/files/16115694/crush.zip)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r397/main.js, line 1057, col 401
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Q.B (https://editor.construct.net/r397/main.js:1057:407) at CCG.Pj.ec.hT.v0 (https://editor.construct.net/r397/main.js:2013:298) at window.SDK.Gfx.IWebGLText.SetFontSize (https://editor.construct.net/r397/main.js:2699:176) at AdaptiveTextInstance.Draw (blob:https://editor.construct.net/d996307e-be06-4a39-ae92-3322f728fda3:80:25) at qxa.AIc.wg (https://editor.construct.net/r397/main.js:2649:118) at d.wg (https://editor.construct.net/r397/projectResources.js:890:200) at d.wg (https://editor.construct.net/r397/projectResources.js:1455:109) at d.wg (https://editor.construct.net/r397/projectResources.js:1409:388) at Kkc (https://editor.construct.net/r397/components/editors/layoutView/layoutView.js:103:331)
Construct version: r397
URL: https://editor.construct.net/
Date: Sat Jul 06 2024 15:35:44 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 14 s

Platform information
Product: Construct 3 r397 (stable)
Browser: Edge 126.0.2592.87
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00005917) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

**Comment by koteelok** [comment]
Закрываю так как не смог воспроизвести ошибку
